import Link from "next/link";
import { ArrowRight, CarFront, Disc3, Filter, Headphones, PackageCheck, SearchCheck, ShieldCheck, Truck } from "lucide-react";
import { VehicleSearch } from "@/components/VehicleSearch";
import { getHomepageContent } from "@/lib/cms";

export default async function Home(){const cms=await getHomepageContent();const hero=cms?.pageBuilder?.find(section=>section.__component==="sections.hero");return <>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow" style={{color:"#84d3ad"}}>{hero?.eyebrow||"Peças automóvel · Portugal"}</span><h1>{hero?.heading||"Encontre as peças certas para o seu carro."}</h1><p>{hero?.body||"Identifique a sua viatura, compare alternativas e compre com informação clara sobre compatibilidade, stock e entrega."}</p><span className={`tag ${cms?"real-tested":"demo"}`}>{cms?"STRAPI · PUBLISHED EDITORIAL":"CMS OFFLINE · LOCAL FALLBACK"}</span><VehicleSearch/></div><div className="hero-aside" aria-hidden><div className="hero-part"><Disc3 size={170} strokeWidth={.6}/></div></div></div></section>
  <section className="trust-strip"><div className="container trust-grid"><div className="trust-item"><ShieldCheck/><div><strong>Compatibilidade controlada</strong><span>Estados claros, sem certezas falsas</span></div></div><div className="trust-item"><Truck/><div><strong>Entrega GLS</strong><span>Estimativa demonstrativa</span></div></div><div className="trust-item"><PackageCheck/><div><strong>Stock visível</strong><span>Base preparada para ERP</span></div></div><div className="trust-item"><Headphones/><div><strong>Apoio em português</strong><span>Quando a escolha precisa de ajuda</span></div></div></div></section>
  <section className="section"><div className="container"><span className="eyebrow">Catálogo inicial</span><h2 className="section-title">Começar pelas peças mais procuradas.</h2><p className="section-copy">Uma estrutura focada para validar o percurso de compra antes de alargar o catálogo.</p><div className="category-grid" style={{marginTop:32}}><Link href="/catalogo?category=Filtros" className="category-card"><span className="tag">MANUTENÇÃO</span><h3>Filtros</h3><p>Óleo, ar, combustível e habitáculo.</p><Filter/></Link><Link href="/catalogo?category=Pastilhas%20de%20travão" className="category-card"><span className="tag">TRAVAGEM</span><h3>Pastilhas</h3><p>Alternativas por marca e posição no veículo.</p><Disc3/></Link><Link href="/catalogo?category=Discos%20de%20travão" className="category-card"><span className="tag">TRAVAGEM</span><h3>Discos</h3><p>Medidas e restrições técnicas em destaque.</p><Disc3/></Link></div></div></section>
  <section className="section" style={{background:"white"}}><div className="container"><div className="product-detail"><div><span className="eyebrow">Por detrás da pesquisa</span><h2 className="section-title">Uma experiência simples. Uma decisão controlada.</h2><p className="section-copy">A plataforma normaliza o resultado do fornecedor, preserva a origem dos dados e pede confirmação quando não existe certeza suficiente.</p><Link href="/architecture" className="btn" style={{marginTop:22}}>Ver arquitetura <ArrowRight size={18}/></Link></div><div className="arch-flow" style={{margin:0}}><div className="arch-node"><CarFront/><strong>Matrícula / VIN / Manual</strong></div><div className="arch-arrow">↓</div><div className="arch-node"><SearchCheck/><strong>Veículo normalizado</strong><span>BASIC → EXACT_VARIANT</span></div><div className="arch-arrow">↓</div><div className="arch-node"><ShieldCheck/><strong>FitmentProvider</strong><span>NÃO CONFIGURADO · confirmar compatibilidade</span></div></div></div></div></section>
  </>}
